config/routes.rb
Rails.application.routes.draw do
  get "errors/not_found"
  get "errors/internal_server_error"
  get "references/index"
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#login', as: :login
  get '/logout', to: 'sessions#destroy'
  get 'contact', to: 'pages#contact'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'my_page' => 'users#my_page'

  root 'tops#top'

  resources :noshis, only: %i[index show] do
    resource :noshi_bookmark, only: %i[create show destroy]
    collection do
      get :bookmarks, to: 'noshi_bookmarks#show'
      get :require_login, to: 'noshi_bookmarks#require_login'
    end
  end

  resources :columns, only: %i[index show] do
    resource :column_bookmark, only: %i[create show destroy]
    collection do
      get :bookmarks, to: 'column_bookmarks#show'
      get :require_login, to: 'column_bookmarks#require_login'
    end
  end

  post 'users/firebase_login', to: 'users/sessions#firebase'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :admin do
    resources :columns, only: %i[new create index show edit update destroy]
    root "tops#top"
  end

  resources :references, only: %i[index]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*path", to: "errors#not_found", via: :all
end

app/models/category.rb
class Category < ApplicationRecord
  validates :use_case, length: { maximum: 100 }
  validates :religion, length: { maximum: 100 }
  validates :type, length: { maximum: 100 }
  has_many :noshis, through: :noshi_categories
  has_many :noshi_categories, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[id use_case religion type created_at updated_at]
  end
  self.inheritance_column = :_type_disabled
end

app/models/column.rb
class Column < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :text, presence: true
  has_many :noshi_columns
  has_many :column_tags, dependent: :destroy
  has_many :noshis, through: :noshi_columns
  has_many :tags, through: :column_tags
  has_many :column_bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :column_bookmarks, source: :user

  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "text", "thumbnail"]
  end
end

app/models/column_bookmark.rb
class ColumnBookmark < ApplicationRecord
  belongs_to :user
  belongs_to :column

  validates :user_id, uniqueness: { scope: :column_id }
end

app/models/column_tag.rb
class ColumnTag < ApplicationRecord
  belongs_to :column
  belongs_to :tag
end

app/models/noshi.rb
class Noshi < ApplicationRecord
  validates :label, presence: true, length: { maximum: 50 }
  validates :knot, presence: true, length: { maximum: 20 }
  validates :color, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :image, presence: true, length: { maximum: 255 }
  has_many :noshi_tags, dependent: :destroy
  has_many :noshi_columns
  has_many :noshi_synonyms, dependent: :destroy
  has_many :noshi_categories, dependent: :destroy
  has_many :categories, through: :noshi_categories
  has_many :tags, through: :noshi_tags
  has_many :columns, through: :noshi_columns
  has_many :synonyms, through: :noshi_synonyms
  has_many :noshi_bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :noshi_bookmarks, source: :user

ransacker :categories_use_case do
  Arel.sql("(SELECT string_agg(categories.use_case, ' ') FROM categories INNER JOIN noshi_categories ON categories.id = noshi_categories.category_id WHERE noshi_categories.noshi_id = noshis.id)")
end

ransacker :categories_religion do
  Arel.sql("(SELECT string_agg(categories.religion, ' ') FROM categories INNER JOIN noshi_categories ON categories.id = noshi_categories.category_id WHERE noshi_categories.noshi_id = noshis.id)")
end

  def self.ransackable_attributes(auth_object = nil)
    %w[id label color knot image description created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[categories synonyms bookmarks noshi_columns noshi_synonyms noshi_tags columns tags]
  end
end

app/models/noshi_bookmark.rb
class NoshiBookmark < ApplicationRecord
  belongs_to :user
  belongs_to :noshi

  validates :user_id, uniqueness: { scope: :noshi_id }
end

app/models/noshi_category.rb
class NoshiCategory < ApplicationRecord
  belongs_to :noshi
  belongs_to :category
end

app/models/noshi_column.rb
class NoshiColumn < ApplicationRecord
  belongs_to :noshi
  belongs_to :column
end

app/models/noshi_synonym.rb
class NoshiSynonym < ApplicationRecord
  belongs_to :noshi
  belongs_to :synonym
end

app/models/noshi_tag.rb
class NoshiTag < ApplicationRecord
  belongs_to :noshi
  belongs_to :tag
end

app/models/reference.rb
class Reference < ApplicationRecord
  validates :title, presence: true
end

app/models/synonym.rb
class Synonym < ApplicationRecord
  validates :word, presence: true, length: { maximum: 255 }
  has_many :noshi_synonyms
  has_many :noshis, through: :noshi_synonyms

  def self.ransackable_attributes(auth_object = nil)
    %w[id word created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[noshis colums noshi_synonyms column_synonyms]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  has_many :noshi_tags
  has_many :noshis, through: :noshi_tags
  has_many :column_tags
  has_many :columns, through: :column_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :noshi_bookmarks, dependent: :destroy
  has_many :bookmark_noshis, through: :noshi_bookmarks, source: :noshi
  has_many :column_bookmarks, dependent: :destroy
  has_many :bookmark_columns, through: :column_bookmarks, source: :column
  validates :email, presence: true, uniqueness: true
  enum role: { general: 0, admin: 1 }

  def noshi_bookmark(noshi)
    bookmark_noshis << noshi
  end

  def noshi_unbookmark(noshi)
    bookmark_noshis.destroy(noshi)
  end

  def noshi_bookmark?(noshi)
    bookmark_noshis.include?(noshi)
  end

  def column_bookmark(column)
    bookmark_columns << column
  end

  def column_unbookmark(column)
    bookmark_columns.destroy(column)
  end

  def column_bookmark?(column)
    bookmark_columns.include?(column)
  end

  def admin?
    self.role == "admin"
  end

  def general?
    self.role == "general"
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/noshies_helper.rb
module NoshiesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">
    <title>Noshiru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    
    <% og_title = content_for?(:og_title) ? yield(:og_title) : "Noshiru" %>
    <% og_description = content_for?(:og_description) ? yield(:og_description) : "うさぎ印の、のし検索サイト" %>
    <% og_image = content_for?(:og_image) ? yield(:og_image) : image_url("ogp_image.png") %>

    <meta property="og:title" content="<%= og_title %>" />
    <meta property="og:description" content="<%= og_description %>" />
    <meta property="og:image" content="<%= og_image %>" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Noshiru"/>

    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<%= og_title %>">
    <meta name="twitter:description" content="<%= og_description %>">
    <meta name="twitter:image" content="<%= og_image %>">
    
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= turbo_include_tags %>
    <%= javascript_importmap_tags %>
    <!-- フォント -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@400;800&display=swap" rel="stylesheet">
  
    <!-- slick-carouselのCSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    <!-- QuillのCSS（CDN） -->
    <script src="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/quill@2.0.3/dist/quill.snow.css" />
  </head>

  <body class="m-plus-rounded-1c-regular overflow-x-hidden">
    <div class="min-h-screen bg-[#0f172a] w-full relative">
      <div
      class="absolute inset-0 z-0"
      style="background: radial-gradient(circle 600px at 50% 50%, rgba(59,130,246,0.3), transparent)"></div>
      <main class="flex-grow flex flex-col items-center justify-center mx-auto z-10 relative">
        <% if user_signed_in? %>
          <%= render 'shared/after_login_header' %>
        <% else %>
          <%= render 'shared/header' %>
        <% end %>
        <%= render 'shared/flash_message' %>
        <%= yield %>
        <%= render 'shared/footer' %>
      </main>
    </div>
  </body>
</html>

app/views/shared/_after_login_header.html.erb
<header class="mt-10 left-0 w-full z-40">
  <div class="flex items-center justify-between w-full px-4">

    <!-- 左側：ロゴとキャッチコピー -->
    <div class="flex flex-col">
      <div class="mb-2 w-[150px] md:w-[200px]">
        <%= link_to root_path do %>
          <%= image_tag 'new_logo.png', class: "w-full h-auto object-contain transition-all duration-300 ease-in-out" %>
        <% end %>
      </div>
    </div>

    <!-- 中央：リンク集（中画面以上で表示） -->
    <ul class="hidden md:flex space-x-6 text-white text-2xl text-center">
      <li class="hover:underline cursor-pointer">Noshiruについて</li>
      <li class="hover:underline cursor-pointer"><%= link_to 'コラム', columns_path %></li>
      <li class="hover:underline cursor-pointer">熨斗紙テンプレート</li>
      <li class="hover:underline cursor-pointer">
        <%= form_with url: logout_path, method: :get do %>
          <%= submit_tag "ログアウト", class: "hover:underline cursor-pointer" %>
        <% end %>
      </li>
    </ul>

    <div class="flex items-center justify-end space-x-4 text-red-500 text-5xl">
      <!-- 右側：矢印アイコン -->
      <%= link_to my_page_path do %>
        <%= image_tag 'my-page-rabbit.png', class: "hover:scale-105 w-20 h-20 md:w-30 md:h-30" %>
      <% end %>

      <div class="md:hidden">
        <!-- 右側：メニューアイコン（三本線） -->
        <button id="menu-bar" class="text-5xl cursor-pointer text-white hover:text-yellow-300 transition-colors duration-300">&#9776;</button>
        <ul id="menu" class="hidden bg-blue-100 flex flex-col space-y-4 mt-4 text-lg text-zinc-700 px-4 py-4 rounded-lg opacity-0 transition-opacity duration-500 ease-in-out">
          <li class="hover:underline cursor-pointer">Noshiruについて</li>
          <li class="hover:underline cursor-pointer"><%= link_to 'コラム', columns_path %></li>
          <li class="hover:underline cursor-pointer">熨斗紙テンプレート</li>
          <li class="hover:underline cursor-pointer">
            <%= form_with url: logout_path, method: :get do %>
              <%= submit_tag "ログアウト", class: "hover:underline cursor-pointer" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_flash_message.html.erb
<% flash.each do |type, message| %>
  <div class="mb-4 px-4 py-3 rounded text-white <%= type == 'notice' ? 'bg-green-500' : 'bg-red-500' %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="mt-20">
  <ul class="relative flex flex-col md:flex-row justify-center items-center space-y-4 md:space-y-0 md:space-x-10 text-sm">
    <li class="hover:text-yellow-300 text-white"><%= link_to 'トップページ', root_path %></li>
    <li class="hover:text-yellow-300 text-white">Noshiruについて</li>
    <li class="hover:text-yellow-300 text-white">お知らせ</li>
    <li class="hover:text-yellow-300 text-white"><%= link_to 'コラム', columns_path %></li>
    <li class="hover:text-yellow-300 text-white">サイトポリシー</li>
    <li class="hover:text-yellow-300 text-white">プライドポリシー</li>
    <li class="hover:text-yellow-300 text-white"><%= link_to '参考文献', references_path %></li>
    <li class="hover:text-yellow-300 text-white"><%= link_to 'お問い合わせ', contact_path %></li>
  </ul>
  <p class="py-5 text-center mt-10 text-white">© 2025 Noshiru</p>
</footer>

app/views/shared/_header.html.erb
<header class="mt-10 left-0 w-full z-40">
  <div class="flex items-center justify-between w-full px-4">

    <!-- 左側：ロゴとキャッチコピー -->
    <div class="flex flex-col">
      <div class="mb-2">
        <%= link_to root_path do %>
          <%= image_tag 'new_logo.png', class: "w-[150px] md:w-[200px] transition-all duration-300 ease-in-out" %>
        <% end %>
      </div>
    </div>

    <!-- 中央：リンク集（中画面以上で表示） -->
    <ul class="hidden md:flex space-x-6 text-white text-2xl text-center">
      <li class="hover:underline cursor-pointer">Noshiruについて</li>
      <li class="hover:underline cursor-pointer"><%= link_to 'コラム', columns_path %></li>
      <li class="hover:underline cursor-pointer">熨斗紙テンプレート</li>
    </ul>

    <div class="flex items-center justify-end space-x-4 text-red-500 text-5xl">
      <!-- 右側：ログインアイコン -->
      <div class="hover:scale-105">
        <%= form_with url: '/auth/google_oauth2', method: :post, data: { turbo: false } do %>
          <button class="gsi-material-button mt-2 items-center justify-center">
            <div class="gsi-material-button-state"></div>
            <div class="gsi-material-button-content-wrapper">
              <div class="gsi-material-button-icon">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
                  <path fill="#EA4335" d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                  <path fill="#4285F4" d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                  <path fill="#FBBC05" d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                  <path fill="#34A853" d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                  <path fill="none" d="M0 0h48v48H0z"></path>
                </svg>
              </div>
              <span class="gsi-material-button-contents">ログイン</span>
              <span style="display: none;">ログイン</span>
            </div>
          </button>
        <% end %>
      </div>

      <div class="md:hidden">
        <!-- 右側：メニューアイコン（三本線） -->
        <button id="menu-bar" class="text-5xl cursor-pointer text-white hover:text-yellow-300 transition-colors duration-300">&#9776;</button>
        <ul id="menu" class="hidden flex flex-col space-y-4 mt-4 text-lg text-white opacity-0 transition-opacity duration-500 ease-in-out">
          <li class="hover:underline cursor-pointer text-white">Noshiruについて</li>
          <li class="hover:underline cursor-pointer text-white"><%= link_to 'コラム', columns_path %></li>
          <li class="hover:underline cursor-pointer text-white">熨斗紙テンプレート</li>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/shared/_search.html.erb
<!-- キーワード検索 -->
<div class="relative bg-yellow-300 rounded-full w-[300px] h-[300px] flex bg-origin-content bg-contain bg-auto bg-center items-center justify-center shadow-md rounded-full">
  <%= form_with url: root_path, method: :get, local: true do |f| %>
    <div class="relative w-[95%] max-w-[280px] mx-auto">
      <%= text_field_tag 'q[keyword]', params.dig(:q, :keyword), placeholder: 'のしキーワード検索', class: 'pl-10 pr-4 py-2 rounded-full w-full shadow-inner text-zinc-800 text-xl text-center bg-zinc-100' %>
      <button type="submit" class="absolute right-10 top-1/2 transform -translate-y-1/2 text-blue-900 hover:text-yellow-400 transition-colors duration-200 z-20">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 absolute left-2 top-1/2 transform -translate-y-1/2 text-zinc-800 cursor-pointer">
          <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
        </svg>
      </button>
    </div>
  <% end %>
</div>

<!-- 詳細検索 -->
<div class="w-full md:w-2/3 text-zinc-800 px-6 py-10 shadow-md rounded-lg bg-white">
  <p class="text-2xl mb-4 text-center">詳細のし検索</p>
  <%= search_form_for @q, url: root_path, method: :get, html: { id: "search-form" } do |f| %>
    <div class="mb-4">
      <%= f.label :label, "表書き", class: "block mb-1" %>
      <%= f.search_field :label_cont, placeholder: '例: 御祝', class: "w-full border rounded px-3 py-2" %>
    </div>

    <div class="mb-4">
      <%= f.label :use_case, "用途", class: "block mb-1" %>
      <%= f.select :categories_use_case_cont, @use_cases.map(&:use_case).uniq.reject(&:blank?).map { |uc| [uc, uc] }, { include_blank: '用途を選択' }, class: "w-full border rounded px-3 py-2 relative z-10" %>
    </div>

    <div class="flex justify-center space-x-4 mt-6">
      <%= f.submit "検索", class: "bg-sky-600 text-white px-6 py-2 rounded-full shadow hover:bg-red-400 relative z-10 cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/shared/_sns.html.erb
<div class="mt-12 pt-6 pb-8">
  <div class="flex justify-center gap-6">
    <%= link_to "https://twitter.com/intent/tweet?url=#{CGI.escape(request.original_url)}&text=#{CGI.escape('のし紙を選ぶなら、うさぎ印🐰のNoshiruをぜひお試しください!!地域差なくどこでも通用する万能型のし検索アプリです🎀')}&hashtags=#{CGI.escape('のし検索,熨斗,うさぎ印,Noshiru')}", target: "_blank", rel: "noopener noreferrer" do %>
      <%= image_tag "x_logo.png", alt: "Twitterで共有", class: "w-20 h-20 opacity-80 hover:opacity-100 transition-opacity" %>
    <% end %>

    <%= link_to "https://social-plugins.line.me/lineit/share?url=#{CGI.escape(request.original_url)}", target: "_blank", rel: "noopener noreferrer" do %>
      <%= image_tag "line-logo.png", alt: "LINEで共有", class: "w-20 h-20 opacity-80 hover:opacity-100 transition-opacity" %>
    <% end %>
  </div>
</div>