config/routes.rb
Rails.application.routes.draw do
  get "errors/not_found"
  get "errors/internal_server_error"
  get "references/index"
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#login', as: :login
  get '/logout', to: 'sessions#destroy'
  get 'contact', to: 'pages#contact'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'my_page' => 'users#my_page'

  root 'tops#top'

  resources :noshis, only: %i[index show] do
    resource :noshi_bookmark, only: %i[create show destroy]
    collection do
      get :bookmarks, to: 'noshi_bookmarks#show'
      get :require_login, to: 'noshi_bookmarks#require_login'
    end
  end

  resources :columns, only: %i[index show] do
    resource :column_bookmark, only: %i[create show destroy]
    collection do
      get :bookmarks, to: 'column_bookmarks#show'
      get :require_login, to: 'column_bookmarks#require_login'
    end
  end

  post 'users/firebase_login', to: 'users/sessions#firebase'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :admin do
    resources :columns, only: %i[new create index show edit update destroy]
    root "tops#top"
  end

  resources :references, only: %i[index]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*path", to: "errors#not_found", via: :all
end

app/models/category.rb
class Category < ApplicationRecord
  validates :use_case, length: { maximum: 100 }
  validates :religion, length: { maximum: 100 }
  validates :type, length: { maximum: 100 }
  has_many :noshis, through: :noshi_categories
  has_many :noshi_categories, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    %w[id use_case religion type created_at updated_at]
  end
  self.inheritance_column = :_type_disabled
end

app/models/column.rb
class Column < ApplicationRecord
  validates :title, presence: true, length: { maximum: 255 }
  validates :text, presence: true
  has_many :noshi_columns
  has_many :column_tags, dependent: :destroy
  has_many :noshis, through: :noshi_columns
  has_many :tags, through: :column_tags
  has_many :column_bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :column_bookmarks, source: :user

  def self.ransackable_associations(auth_object = nil)
    ["tags"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["title", "text", "thumbnail"]
  end
end

app/models/column_bookmark.rb
class ColumnBookmark < ApplicationRecord
  belongs_to :user
  belongs_to :column

  validates :user_id, uniqueness: { scope: :column_id }
end

app/models/column_tag.rb
class ColumnTag < ApplicationRecord
  belongs_to :column
  belongs_to :tag
end

app/models/noshi.rb
class Noshi < ApplicationRecord
  validates :label, presence: true, length: { maximum: 50 }
  validates :knot, presence: true, length: { maximum: 20 }
  validates :color, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :image, presence: true, length: { maximum: 255 }
  has_many :noshi_tags, dependent: :destroy
  has_many :noshi_columns
  has_many :noshi_synonyms, dependent: :destroy
  has_many :noshi_categories, dependent: :destroy
  has_many :categories, through: :noshi_categories
  has_many :tags, through: :noshi_tags
  has_many :columns, through: :noshi_columns
  has_many :synonyms, through: :noshi_synonyms
  has_many :noshi_bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :noshi_bookmarks, source: :user

ransacker :categories_use_case do
  Arel.sql("(SELECT string_agg(categories.use_case, ' ') FROM categories INNER JOIN noshi_categories ON categories.id = noshi_categories.category_id WHERE noshi_categories.noshi_id = noshis.id)")
end

ransacker :categories_religion do
  Arel.sql("(SELECT string_agg(categories.religion, ' ') FROM categories INNER JOIN noshi_categories ON categories.id = noshi_categories.category_id WHERE noshi_categories.noshi_id = noshis.id)")
end

  def self.ransackable_attributes(auth_object = nil)
    %w[id label color knot image description created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[categories synonyms bookmarks noshi_columns noshi_synonyms noshi_tags columns tags]
  end
end

app/models/noshi_bookmark.rb
class NoshiBookmark < ApplicationRecord
  belongs_to :user
  belongs_to :noshi

  validates :user_id, uniqueness: { scope: :noshi_id }
end

app/models/noshi_category.rb
class NoshiCategory < ApplicationRecord
  belongs_to :noshi
  belongs_to :category
end

app/models/noshi_column.rb
class NoshiColumn < ApplicationRecord
  belongs_to :noshi
  belongs_to :column
end

app/models/noshi_synonym.rb
class NoshiSynonym < ApplicationRecord
  belongs_to :noshi
  belongs_to :synonym
end

app/models/noshi_tag.rb
class NoshiTag < ApplicationRecord
  belongs_to :noshi
  belongs_to :tag
end

app/models/reference.rb
class Reference < ApplicationRecord
  validates :title, presence: true
end

app/models/synonym.rb
class Synonym < ApplicationRecord
  validates :word, presence: true, length: { maximum: 255 }
  has_many :noshi_synonyms
  has_many :noshis, through: :noshi_synonyms

  def self.ransackable_attributes(auth_object = nil)
    %w[id word created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[noshis colums noshi_synonyms column_synonyms]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name, presence: true, length: { maximum: 255 }
  has_many :noshi_tags
  has_many :noshis, through: :noshi_tags
  has_many :column_tags
  has_many :columns, through: :column_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :noshi_bookmarks, dependent: :destroy
  has_many :bookmark_noshis, through: :noshi_bookmarks, source: :noshi
  has_many :column_bookmarks, dependent: :destroy
  has_many :bookmark_columns, through: :column_bookmarks, source: :column
  validates :email, presence: true, uniqueness: true
  enum role: { general: 0, admin: 1 }

  def noshi_bookmark(noshi)
    bookmark_noshis << noshi
  end

  def noshi_unbookmark(noshi)
    bookmark_noshis.destroy(noshi)
  end

  def noshi_bookmark?(noshi)
    bookmark_noshis.include?(noshi)
  end

  def column_bookmark(column)
    bookmark_columns << column
  end

  def column_unbookmark(column)
    bookmark_columns.destroy(column)
  end

  def column_bookmark?(column)
    bookmark_columns.include?(column)
  end

  def admin?
    self.role == "admin"
  end

  def general?
    self.role == "general"
  end
end

app/controllers/column_bookmarks_controller.rb
class ColumnBookmarksController < ApplicationController
  before_action :require_login, only: [:create, :show, :destroy]

  def create
    @column = Column.find(params[:column_id])
    current_user.column_bookmark(@column)
    respond_to do |format|
      format.turbo_stream
    end
  end

  def show
    @columns = current_user.bookmark_columns
  end

  def destroy
    @column = Column.find(params[:column_id])
    current_user.column_unbookmark(@column)
    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/helpers/columns_helper.rb
module ColumnsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/noshies_helper.rb
module NoshiesHelper
end

app/helpers/synonyms_helper.rb
module SynonymsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/column_bookmarks/_column_bookmark_button.html.erb
<!-- 星アイコン -->
<% if current_user %>
  <div id="bookmark-button-for-column-<%= column.id %>">
    <% if current_user.column_bookmark?(column) %>
      <%= link_to column_column_bookmark_path(column),
                data: { turbo_method: :delete, turbo_stream: true },
                class: "inline-block" do %>
        <span class="cursor-pointer hover:scale-110 w-[10px] h-[10px]">
          <%= image_tag 'usamark2.png' %>
        </span>
      <% end %>
    <% else %>
      <%= link_to column_column_bookmark_path(column),
                data: { turbo_method: :post, turbo_stream: true },
                class: "inline-block" do %>
        <span class="cursor-pointer hover:scale-110 w-[10px] h-[10px]">
          <%= image_tag 'usamark1.png' %>
        </span>
      <% end %>
    <% end %>
  </div>
<% else %>
  <%= form_with url: '/auth/google_oauth2', method: :post, data: { turbo: false } do %>
    <button class="cursor-pointer hover:scale-110 w-[10px] h-[10px]">
      <%= image_tag 'usamark1.png' %>
    </button>
  <% end %>
<% end %>

app/views/column_bookmarks/create.turbo_stream.erb
<%= turbo_stream.replace "bookmark-button-for-column-#{@column.id}" do %>
  <%= render partial: "column_bookmarks/column_bookmark_button", formats: [:html], locals: { column: @column } %>
<% end %>

app/views/column_bookmarks/destroy.turbo_stream.erb
<%= turbo_stream.replace "bookmark-button-for-column-#{@column.id}" do %>
  <%= render partial: "column_bookmarks/column_bookmark_button", formats: [:html], locals: { column: @column } %>
<% end %>

app/views/column_bookmarks/show.html.erb
<div class="max-w-5xl mx-auto px-4">
  <% if @columns.present? %>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 space-y-6">
      <% @columns.each do |column| %>
        <div class="shadow rounded overflow-hidden w-full">
          <div class="flex flex-col">
            <div class="p-6 flex flex-col space-y-10">
              <%= render 'column_bookmarks/column_bookmark_button', column: column %>
              <%= link_to column_path(column) do %>
                <div class="text-3xl text-white text-center"><%= column.title %></div>
              <% end %>
              <div class="w-full relative z-19">
                <%= link_to column_path(column) do %>
                  <%= image_tag "#{column.thumbnail}", class: "w-full h-auto object-cover" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <P class="mt-5 text-white text-center text-3xl">ブックマークされたコラムはまだありません。</p>
  <% end %>
</div>