config/routes.rb
Rails.application.routes.draw do
  get "errors/not_found"
  get "errors/internal_server_error"
  get "references/index"
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/login', to: 'sessions#login', as: :login
  get '/logout', to: 'sessions#destroy'
  get 'contact', to: 'pages#contact'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get 'my_page' => 'users#my_page'

  root 'tops#top'

  resources :noshis, only: %i[index show] do
    resource :noshi_bookmark, only: %i[create show destroy]
    collection do
      get :bookmarks, to: 'noshi_bookmarks#show'
      get :require_login, to: 'noshi_bookmarks#require_login'
    end
  end

  resources :columns, only: %i[index show] do
    resource :column_bookmark, only: %i[create show destroy]
    collection do
      get :bookmarks, to: 'column_bookmarks#show'
      get :require_login, to: 'column_bookmarks#require_login'
    end
  end

  post 'users/firebase_login', to: 'users/sessions#firebase'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  namespace :admin do
    resources :columns, only: %i[new create index show edit update destroy]
    root "tops#top"
  end

  resources :references, only: %i[index]

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  match "*path", to: "errors#not_found", via: :all
end

app/models/noshi.rb
class Noshi < ApplicationRecord
  validates :label, presence: true, length: { maximum: 50 }
  validates :knot, presence: true, length: { maximum: 20 }
  validates :color, presence: true, length: { maximum: 20 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :image, presence: true, length: { maximum: 255 }
  has_many :noshi_tags, dependent: :destroy
  has_many :noshi_columns
  has_many :noshi_synonyms, dependent: :destroy
  has_many :noshi_categories, dependent: :destroy
  has_many :categories, through: :noshi_categories
  has_many :tags, through: :noshi_tags
  has_many :columns, through: :noshi_columns
  has_many :synonyms, through: :noshi_synonyms
  has_many :noshi_bookmarks, dependent: :destroy
  has_many :bookmarked_by_users, through: :noshi_bookmarks, source: :user

ransacker :categories_use_case do
  Arel.sql("(SELECT string_agg(categories.use_case, ' ') FROM categories INNER JOIN noshi_categories ON categories.id = noshi_categories.category_id WHERE noshi_categories.noshi_id = noshis.id)")
end

ransacker :categories_religion do
  Arel.sql("(SELECT string_agg(categories.religion, ' ') FROM categories INNER JOIN noshi_categories ON categories.id = noshi_categories.category_id WHERE noshi_categories.noshi_id = noshis.id)")
end

  def self.ransackable_attributes(auth_object = nil)
    %w[id label color knot image description created_at updated_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[categories synonyms bookmarks noshi_columns noshi_synonyms noshi_tags columns tags]
  end
end

app/controllers/noshis_controller.rb
class NoshisController < ApplicationController
  def index
    # joinで検索対象に含める
    @q = Noshi.joins(:categories, :synonyms).ransack(params[:q])
    # includesで検索結果にも反映
    @noshis = @q.result(distinct: true).includes(:categories, :synonyms)
    @use_cases = Category.where.not(use_case: [nil, '']).select(:use_case).distinct.order(:use_case)
    #キーワード検索判定
    keyword = :label_or_description_or_synonyms_word_or_categories_use_case_or_categories_religion_or_columns_title_or_columns_text_cont
    @keyword_search = params[:q].present? && params[:q][keyword].present?
  end

  def show
    @q = Noshi.joins(:categories, :synonyms).ransack(params[:q])
    @noshis = @q.result(distinct: true).includes(:category, :synonyms)
    @use_cases = Category.select(:use_case).distinct.order(:use_case)
    @religions = Category.select(:religion).distinct.order(:religion)
    @noshi = Noshi.find(params[:id])
    # @noshi.tag_idsは現在表示中の熨斗が持つタグのID一覧
    # where(tags: { id: @noshi.tag_ids })で同じタグを持つ熨斗抽出
    # where.not(id: @noshi.id)で自分を除外
    @related_noshis = Noshi.joins(:tags).where(tags: { id: @noshi.tag_ids }).where.not(id: @noshi.id).group('noshis.id').order('COUNT(tags.id) DESC')
    @related_columns = Column.joins(:tags).where(tags: { id: @noshi.tag_ids }).distinct
  end

  def bookmarks
    @q = current_user.bookmark_noshis.ransack(params[:q])
    @bookmark_noshis = @q.result(distinct: true).includes(:user).order(created_at: :desc)
  end
end

app/views/noshis/_unbookmark.html.erb
<%= form_with url: noshi_bookmark_path(noshi, current_user.bookmarks.find_by(noshi_id: noshi.id)), method: :delete, data: { turbo_stream: true } do %>
  <button type="submit" class="cursor-pointer">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-10 text-yellow-400 transition">
      <path stroke-linecap="round" stroke-linejoin="round" d="M11.48 3.499a.562.562 0 0 1 1.04 0l2.125 5.111a.563.563 0 0 0 .475.345l5.518.442c.499.04.701.663.321.988l-4.204 3.602a.563.563 0 0 0-.182.557l1.285 5.385a.562.562 0 0 1-.84.61l-4.725-2.885a.562.562 0 0 0-.586 0L6.982 20.54a.562.562 0 0 1-.84-.61l1.285-5.386a.562.562 0 0 0-.182-.557l-4.204-3.602a.562.562 0 0 1 .321-.988l5.518-.442a.563.563 0 0 0 .475-.345L11.48 3.5Z" />
    </svg>
  </button>
<% end %>

app/views/noshis/show.html.erb
<div class="flex flex-col flex-grow items-center space-y-10 py-10 justify-center max-w-screen mx-auto relative z-10">
  <%= render 'shared/search' %>
  <div class="max-w-5xl mx-auto px-4 bg-transparent">
    <div class="space-y-6">
      <div id="noshi-id-<%= @noshi.id %>" class="shadow rounded overflow-hidden w-full">
        <div class="flex flex-col lg:flex-row">
          <div class="lg:w-1/2 w-full">
            <%= image_tag @noshi.image, class: "w-full h-auto object-cover" %>
          </div>
          <div class="lg:w-1/2 w-full p-6 flex flex-col justify-start space-y-10 text-zinc-800">
            <div class="text-5xl text-white"><%= @noshi.label %></div>
            <div class="flex flex-row flex-wrap gap-4">
              <% @noshi.categories.each do |category| %>
                <% if category.type.present? || category.religion.present? %>
                  <div class="flex flex-row space-x-4 bg-yellow-300 rounded-full px-4 py-2 text-zinc-700 text-xl">
                    <% if category.type.present? %>
                      <p>贈り物のタイプ: <%= category.type %></p>
                    <% end %>
                    <% if category.religion.present?  %>
                      <p>宗教: <%= category.religion %></p>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="text-2xl text-white">水引の種類:<%= @noshi.knot %></div>
            <div class="text-2xl text-white">文字の色:<%= @noshi.color %></div>
            <div class="text-xl text-white"><%= @noshi.description %></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @related_noshis.present? %>
  <h2 class="text-lg mt-6 text-white">関連熨斗</h2>
  <div class="max-w-screen overflow-x-auto overflow-hidden overflow-x-scroll scroll-smooth flex space-x-4 space-y-4 mt-4 pb-4">
    <% @related_noshis.each do |related| %>
      <%= link_to noshi_path(related), class: "block min-w-[180px] md:min-w-[220px] flex-shrink-0 relative z-10" do %>
        <%= image_tag related.image, class: "w-[300px] h-auto rounded-lg shadow-md transform duration-300 hover:scale-105" %>
      <% end %>
    <% end %>
  </div>
<% end %>

<% if @related_columns.present? %>
  <h2 class="text-lg mt-6 text-white">関連コラム</h2>
  <div class="max-w-screen overflow-x-auto overflow-hidden overflow-x-scroll scroll-smooth flex space-x-4 space-y-4 mt-4 pb-4">
    <% @related_columns.each do |related| %>
      <%= link_to column_path(related), class: "block min-w-[180px] md:min-w-[220px] flex-shrink-0 relative z-10" do %>
        <%= image_tag related.thumbnail, class: "w-[300px] h-auto rounded-lg shadow-md transform duration-300 hover:scale-105" %>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= render 'shared/sns' %>